/RunAction/FileName group-22
# He3 Source:
# Pos X Box:
/gps/particle neutron
/gps/pos/type Volume 
/gps/pos/shape Para
/gps/pos/halfx 1 cm
/gps/pos/halfy 2.27 cm
/gps/pos/halfz 5 cm
/gps/pos/centre 4.27 0 0 cm
/gps/ang/type iso
/gps/energy 2.97e-1 MeV
# Neg X box:
/gps/source/add 1
/gps/particle neutron
/gps/pos/type Volume 
/gps/pos/shape Para
/gps/pos/halfx 1 cm
/gps/pos/halfy 2.27 cm
/gps/pos/halfz 5 cm
/gps/pos/centre -4.27 0 0 cm
/gps/ang/type iso
/gps/energy 2.97e-1 MeV
# Pos Y box:
/gps/source/add 2.322
/gps/particle neutron
/gps/pos/type Volume 
/gps/pos/shape Para
/gps/pos/halfx 5.27 cm
/gps/pos/halfy 1 cm
/gps/pos/halfz 5 cm
/gps/pos/centre 0 3.27 0 cm
/gps/ang/type iso
/gps/energy 2.97e-1 MeV
# Neg Y box:
/gps/source/add 2.322
/gps/particle neutron
/gps/pos/type Volume 
/gps/pos/shape Para
/gps/pos/halfx 5.27 cm
/gps/pos/halfy 1 cm
/gps/pos/halfz 5 cm
/gps/pos/centre 0 -3.27 0 cm
/gps/ang/type iso
/gps/energy 2.97e-1 MeV
/run/beamOn 100000000